@startuml

hide circle
hide stereotype
hide members
hide methods

skinparam linetype ortho

skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}

legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend

class "LMCzBodyKOrderCz" <<LogicalModel>> [[StructureDefinition-LMBodyKOrder.html]]

class "KOrderServiceRequestCz" <<Profile>> [[StructureDefinition-KOrderServiceRequestCz.html]]
"LMCzBodyKOrderCz" <|. "KOrderServiceRequestCz"

class "CZ_Encounter" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-encounter-core.html]]
"LMCzBodyKOrderCz" <|. "CZ_Encounter"
"KOrderServiceRequestCz" -d[hidden]-> "CZ_Encounter"

class "CZ_Coverage" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-coverage.html]]
"LMCzBodyKOrderCz" <|. "CZ_Coverage"
"CZ_Encounter" -d[hidden]-> "CZ_Coverage"

class "CZ_AppointmentOrder" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-appointmentOrder.html]]
"LMCzBodyKOrderCz" <|. "CZ_AppointmentOrder"
"CZ_Coverage" -d[hidden]-> "CZ_AppointmentOrder"

class "CZ_ConditionCore" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-condition-core.html]]
"LMCzBodyKOrderCz" <|. "CZ_ConditionCore"
"CZ_AppointmentOrder" -d[hidden]-> "CZ_ConditionCore"

class "CZ_MedicationStatement" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-MedicationStatement.html]]
"LMCzBodyKOrderCz" <|. "CZ_MedicationStatement"
"CZ_ConditionCore" -d[hidden]-> "CZ_MedicationStatement"

class "CZ_DeviceUseStatement" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-deviceusestatement.html]]
"LMCzBodyKOrderCz" <|. "CZ_DeviceUseStatement"
"CZ_MedicationStatement" -d[hidden]-> "CZ_DeviceUseStatement"

class "CZ_AllergyIntolerance" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-allergyIntolerance.html]]
"LMCzBodyKOrderCz" <|. "CZ_AllergyIntolerance"
"CZ_DeviceUseStatement" -d[hidden]-> "CZ_AllergyIntolerance"

class "CZ_Flag" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition/cz-flag.html]]
"LMCzBodyKOrderCz" <|. "CZ_Flag"
"CZ_AllergyIntolerance" -d[hidden]-> "CZ_Flag"

class "CZ_BodyWeight" <<Profile>> [[StructureDefinition-cz-bodyweight.html]]
"LMCzBodyKOrderCz" <|. "CZ_BodyWeight"
"CZ_Flag" -d[hidden]-> "CZ_BodyWeight"

class "CZ_BodyHeight" <<Profile>> [[StructureDefinition-cz-bodyheight.html]]
"LMCzBodyKOrderCz" <|. "CZ_BodyHeight"
"CZ_BodyWeight" -d[hidden]-> "CZ_BodyHeight"

class "KOrderCompositionCz" <<Profile>> [[StructureDefinition-KOrderCompositionCz.html]]
"LMCzBodyKOrderCz" <|. "KOrderCompositionCz"
"CZ_BodyHeight" -d[hidden]-> "KOrderCompositionCz"

class "BundleOrderCz" <<Profile>> [[StructureDefinition-BundleOrderCz.html]]
"LMCzBodyKOrderCz" <|. "BundleOrderCz"
"KOrderCompositionCz" -d[hidden]-> "BundleOrderCz"

@enduml