@startuml

hide circle
hide stereotype
hide members
hide methods

skinparam linetype ortho

skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}

legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend

class "LMHeaderOrder" <<LogicalModel>> [[StructureDefinition-LMHeaderOrder.html]]

class "CZ_PatientCore" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-patient-core.html]]
"LMHeaderOrder" <|. "CZ_PatientCore"

class "CZ_PractitionerRoleOrder" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-CZ_PractitionerRoleOrder.html]]
"LMHeaderOrder" <|. "CZ_PractitionerRoleOrder"
"CZ_PatientCore" -d[hidden]-> "CZ_PractitionerRoleOrder"

class "CZ_PractitionerCore" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-practitioner-core.html]]
"LMHeaderOrder" <|. "CZ_PractitionerCore"
"CZ_PractitionerRoleOrder" -d[hidden]-> "CZ_PractitionerCore"

class "CZ_Coverage" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-coverage.html]]
"LMHeaderOrder" <|. "CZ_Coverage"
"CZ_PractitionerCore" -d[hidden]-> "CZ_Coverage"

class "CZ_Encounter" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-encounter-core.html]]
"LMHeaderOrder" <|. "CZ_Encounter"
"CZ_Coverage" -d[hidden]-> "CZ_Encounter"

class "CZ_OrganizationCore" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-organization-core.html]]
"LMHeaderOrder" <|. "CZ_OrganizationCore"
"CZ_Encounter" -d[hidden]-> "CZ_OrganizationCore"

class "CZ_Provenance" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-provenance.html]]
"LMHeaderOrder" <|. "CZ_Provenance"
"CZ_OrganizationCore" -d[hidden]-> "CZ_Provenance"

class "KOrderServiceRequestCz" <<Profile>> [[StructureDefinition-KOrderServiceRequestCz.html]]
"LMHeaderOrder" <|. "KOrderServiceRequestCz"
"CZ_Provenance" -d[hidden]-> "KOrderServiceRequestCz"

class "KOrderCompositionCz" <<Profile>> [[StructureDefinition-KOrderCompositionCz.html]]
"LMHeaderOrder" <|. "KOrderCompositionCz"
"KOrderServiceRequestCz" -d[hidden]-> "KOrderCompositionCz"

class "BundleOrderCz" <<Profile>> [[StructureDefinition-BundleOrderCz.html]]
"LMHeaderOrder" <|. "BundleOrderCz"
"KOrderCompositionCz" -d[hidden]-> "BundleOrderCz"

@enduml