@startmindmap 
skinparam topurl StructureDefinition-

* Žádanka
**[#EEEEAE] [[LMHeaderOrder.html Hlavička žádanky]]
**[#EEEEAE] [[LMBodyOrder.html Tělo žádanky]]
** [[LMPresentedFormOrderCz.html Vizuální podoba dokumentu]]
** [[LMPresentedFormOrderCz.html Přílohy]]

@endmindmap