RuleSet: OrderServiceRequestSupportingInformation
* supportingInfo ^short = "Clinical context for this requested service"
* supportingInfo ^definition = "References to existing clinical information used to assess, plan or perform this particular requested service. Select information relevant to this ServiceRequest, such as measurements, medication, allergies, alerts, mobility or an implant. The list provides clinical context in addition to the indication recorded in reasonCode or reasonReference."
* supportingInfo ^requirements = "All permitted resource types share one unsliced list without per-type slice cardinalities. General observations use CZ_MedicalTestResultCore; medication use and administration use CZ_MedicationStatementCore and CZ_MedicationAdministrationCore. Preserve the clinical status, date and dosage of each referenced resource."
* supportingInfo ^comment = "Composition sections organize the complete order document; supportingInfo explicitly links a clinical resource to this individual service. Information in a Composition section is not automatically assigned to every ServiceRequest. When both relationships are relevant, reference the same resource instance from the section and the ServiceRequest. Do not create duplicate clinical resources. References must satisfy the allowed target profiles. Use Encounter for supporting encounter context and ServiceRequest.encounter for the encounter in which the request was made. Use DeviceUseStatement for device use, referencing Device through its device element. In FT, Goal describes the expected outcome; Observation describes the current state. A differential diagnosis should have Condition.verificationStatus populated. See [usage guidance](background.html#supporting-information)."
* reasonReference ^definition = "References to conditions that directly justify the requested service. Use supportingInfo for additional conditions or other clinical facts that influence assessment or provision of that service."
* reasonCode ^definition = "Coded or textual indication explaining why this service is requested. Use reasonReference when the indication is represented by an existing Condition resource."
* note ^definition = "Additional free-text comments about this requested service. Where a relevant clinical fact is available as a supported structured resource, reference it through supportingInfo rather than documenting it only in a note."

RuleSet: OrderCompositionSupportingInformation
* section[supportingInformation].entry ^comment = "Include established historical or long-term conditions and differential diagnoses as CZ_ConditionCore resources. A differential diagnosis should have Condition.verificationStatus populated. Preserve status, timing and dose for medication use or administration. Reference the same resources from ServiceRequest.supportingInfo where relevant; use reasonReference for a direct indication."
* section[supportingInformation] ^comment = "Use this section to make relevant clinical context available in the order document. Its entries do not automatically populate ServiceRequest.supportingInfo. When a fact is relevant to a specific requested service, also link the same resource from that ServiceRequest. Keep the shared A.3.1 clinical data here for both K and FT. Use clinicalQuestion for the indication, carePlan for planned care and medicalDevices for device use; specialized sections describe A.3.2 content. See [usage guidance](background.html#supporting-information)."
* section[supportingInformation].text ^definition = "Human-readable summary of the supporting clinical context. Keep the narrative consistent with the structured entries, including relevant dates and qualifications. An omitted section or entry does not assert the absence of clinical findings."
* section[supportingInformation].entry ^definition = "References to the structured clinical resources summarized by this section. Reuse resource instances already referenced elsewhere in the document. All allowed resource types share one unsliced list. General observations use CZ_MedicalTestResultCore; medication use and administration use CZ_MedicationStatementCore and CZ_MedicationAdministrationCore. CarePlan resources belong in section[carePlan]."
* section[orderInformation] ^comment = "This section identifies the requested ServiceRequest instances. Each request carries its own indication and links to the supporting resources relevant to that service; the document-level clinical sections provide the organized presentation of the order."
* section[medicalDevices] ^comment = "Place device-use information here at document level. If an implant or device affects a particular requested service, also reference the same DeviceUseStatement from ServiceRequest.supportingInfo. Reference the Device through DeviceUseStatement.device."
