Logical: CompleteModelValidation
Parent: Base
Title: "Complete model validation"
Description: "Round-trip validation of all expanded elements"
* hlavicka 1..1 Base "A.1 - Hlavička" "Hlavička dokumentu K-žádanky."
* hlavicka.subjekt 1..1 Base "A.1.1 - Identifikace pacienta  A.1.2 Kontaktní informace pacienta/subjektu" "Identifikace pacienta/subjektu a jeho kontaktních informací"
* hlavicka.subjekt.identifikace 1..1 Base "A.1.1 - Identifikace pacienta/subjektu" "Identifikace pacienta/subjektu"
* hlavicka.subjekt.identifikace.jmeno 1..* string "A.1.1.1 - Jméno" "Křestní jméno pacienta."
* hlavicka.subjekt.identifikace.prijmeni 1..* string "A.1.1.2 - Příjmení" "Příjmení pacienta."
* hlavicka.subjekt.identifikace.datumNarozeni 1..1 dateTime "A.1.1.3 - Datum narození" "Datum, případně i čas narození."
* hlavicka.subjekt.identifikace.datumUmrti 0..1 dateTime "A.1.1.4 - Datum úmrtí" "Datum, případně i čas smrti."
* hlavicka.subjekt.identifikace.identifikator 1..* Identifier "A.1.1.5 - Identifikátor" "Typ identifikátoru a identifikátor osoby. Identifikátor musí být unikátní v rámci daného typu identifikátoru. Povinné je zadání alespoň jednoho národního či mezinárodního identifikátoru (rodné číslo, číslo pasu apod.)"
* hlavicka.subjekt.identifikace.statniObcanstvi 0..* CodeableConcept "A.1.1.6 - Státní občanství" "Státní občanství dle zákona 186/2013. Státní občanství, jak je uváděno na oficiálních dokladech k prokázání identity."
* hlavicka.subjekt.identifikace.pohlavi 1..1 CodeableConcept "A.1.1.7 - Pohlaví" "Úřední/administrativní pohlaví (pohlaví uváděné v dokladech pro úřední účely). Biologické pohlaví pacienta, které může být odlišné od pohlaví administrativního může být vedeno v jiných částech zdravotnické dokumentace."
* hlavicka.subjekt.identifikace.pohlaviProKlinickeUcely 0..1 CodeableConcept "A.1.1.8 - Pohlaví pro klinické použití" "Běžně se uvádí jen pohlaví úřední, pohlaví pro klinické použití je fakultativní - výjimečné. Pokud je vyplněno pracuje se s ním přednostně v klinické praxi - např. při výběru ref. mezí u škál atd."
* hlavicka.subjekt.identifikace.komunikacniJazyk 0..1 CodeableConcept "A.1.1.9 - Komunikační jazyk" "Jazyk (jazyky) v nichž pacient komunikuje"
* hlavicka.subjekt.identifikace.handicap 0..* string "A.1.1.10 - Handicap" "Handicap pacienta (hluchý, apod.)"
* hlavicka.subjekt.kontakt 0..1 Base "A.1.2 - Kontaktní informace pacienta" "Kontaktní informace pacienta"
* hlavicka.subjekt.kontakt.adresa 0..* Address "A.1.2.1 - Adresa" "Poštovní, domácí a/nebo kancelářské adresa. Adresy jsou vždy sekvence částí adresy (např. řádek adresy, země, PSČ, město), i když se formát poštovní adresy může lišit v závislosti na zemi. Adresa může obsahovat informaci o typu adresy; pokud tento atribut není přítomen, předpokládá se, že jde o výchozí adresu použitelnou pro jakýkoli účel."
* hlavicka.subjekt.kontakt.telekom 0..* ContactPoint "A.1.2.2 - Telekom" "Telekomunikační kontakt (e-mail, telefon atp.)."
* hlavicka.subjekt.kontakt.preferovanyLekar 0..* Base "A.1.2.3 - Preferovaný lékař - Registrující praktický lékař, případně jiný lékař, který může poskytovat informace o pacientovi. Zvláště potřebné u pacientů s vzácným onemocněním." "A.1.2.3 - Preferovaný lékař - Registrující praktický lékař, případně jiný lékař, který může poskytovat informace o pacientovi. Zvláště potřebné u pacientů s vzácným onemocněním."
* hlavicka.subjekt.kontakt.preferovanyLekar.identifikator 1..1 Identifier "A.1.2.3.1 - Identifikátor preferovaného lékaře" "Identifikační číslo zdravotnického pracovníka dle Národního registru zdravotnických pracovníků."
* hlavicka.subjekt.kontakt.preferovanyLekar.jmeno 1..1 HumanName "A.1.2.3.2 - Jméno preferovaného lékaře" "Jméno lékaře, u kterého je pacient v péči, nebo který pacienta eviduje."
* hlavicka.subjekt.kontakt.preferovanyLekar.specializace 0..* CodeableConcept "A.1.2.3.3 - Specializace preferovaného lékaře" "Specializace lékaře (Praktické lékařství pro děti a dorost, Praktické lékařství pro dospělé, interní lékařství, gynekologie a porodnictví apod.)"
* hlavicka.subjekt.kontakt.preferovanyLekar.organizace 0..1 Base "A.1.2.3.4 - Organizace preferovaného lékaře" "Identifikátor a název poskytovatele, kterého lékař reprezentuje"
* hlavicka.subjekt.kontakt.preferovanyLekar.adresa 0..1 Address "A.1.2.3.5 - Adresa preferovaného lékaře" "Poštovní, domácí a/nebo kancelářské adresa. Adresy jsou vždy sekvence částí adresy (např. řádek adresy, země, PSČ, město), i když se formát poštovní adresy může lišit v závislosti na zemi. Adresa může obsahovat informaci o typu adresy; pokud tento atribut není přítomen, předpokládá se, že jde o výchozí adresu použitelnou pro jakýkoli účel."
* hlavicka.subjekt.kontakt.preferovanyLekar.telekom 0..* ContactPoint "A.1.2.3.6 - Telekom preferovaného lékaře" "Telekomunikační kontakt (e-mail, telefon atp.)."
* hlavicka.subjekt.kontakt.kontaktniOsoba 0..* Base "A.1.2.4 - Zákonní zástupci a další kontaktní osoby" "Zákonní zástupci a další kontaktní osoby"
* hlavicka.subjekt.kontakt.kontaktniOsoba.typ 0..1 CodeableConcept "A.1.2.4.1 - Typ kontaktu" "Typ kontaktní osoby rozlišující emergentní kontakty, zákonné zástupce a ostatní osoby se vztahem k pacientovi."
* hlavicka.subjekt.kontakt.kontaktniOsoba.vztah 0..1 CodeableConcept "A.1.2.4.2 - Vztah k pacientovi" "Vztah osoby k pacientovi (otec, syn, dcera atp.)"
* hlavicka.subjekt.kontakt.kontaktniOsoba.identifikator 0..* Identifier "A.1.2.4.3 - Identifikátor osoby" "Identifikátor kontaktní osoby"
* hlavicka.subjekt.kontakt.kontaktniOsoba.jmeno 1..* string "A.1.2.4.4 - Jméno osoby" "Jméno kontaktní osoby."
* hlavicka.subjekt.kontakt.kontaktniOsoba.prijmeni 1..* string "A.1.2.4.5 - Příjmení osoby" "Příjmení kontaktní osoby."
* hlavicka.subjekt.kontakt.kontaktniOsoba.adresa 0..1 Address "A.1.2.4.6 - Adresa" "Poštovní, domácí a/nebo kancelářské adresa. Adresy jsou vždy sekvence částí adresy (např. řádek adresy, země, PSČ, město), i když se formát poštovní adresy může lišit v závislosti na zemi. Adresa může obsahovat informaci o typu adresy; pokud tento atribut není přítomen, předpokládá se, že jde o výchozí adresu použitelnou pro jakýkoli účel."
* hlavicka.subjekt.kontakt.kontaktniOsoba.telekom 0..* ContactPoint "A.1.2.4.7 - Telekom" "Telekomunikační kontakt (e-mail, telefon atp.)."
* hlavicka.zdravotniPojisteni 0..1 Base "A.1.3 - Zdravotní pojištění" "Informace o zdravotním pojištění."
* hlavicka.zdravotniPojisteni.kod 0..1 Identifier "A.1.4.1 - Kód zdravotní pojišťovny" "Kód zdravotní pojišťovny."
* hlavicka.zdravotniPojisteni.nazev 0..1 string "A.1.3.2 - Název zdravotní pojišťovny" "Název zdravotní pojišťovny"
* hlavicka.zdravotniPojisteni.cisloPojistence 0..1 Identifier "A.1.3.3 - Číslo zdravotního pojištění" "Číslo pojištěnce."
* hlavicka.uhrada 1..1 Base "A.1.4 - Úhrada" "Informace o způsobu úhrady objednávky vyšetření."
* hlavicka.uhrada.method 1..1 CodeableConcept "A.1.4.1 - Způsob úhrady" "Způsob úhrady objednávky (zdravotní pojištění, hradí pacient, jiný)."
* hlavicka.uhrada.infoOPlatci 0..1 Base "A.1.4.2 - Informace o plátci" "Identifikační údaje plátce a doplňující informace, pokud jde o jinou úhradu než ze zdravotního pojištění. Identifikační údaje obsahují identifikátor, název organizace či jméno plátce, adresu plátce a telekomunikační spojení."
* hlavicka.uhrada.infoOPlatci.jmeno 0..1 HumanName "A.1.4.2.1 - Jméno plátce" "Jméno a příjmení plátce"
* hlavicka.uhrada.infoOPlatci.idOrganizace 0..* Identifier "A.1.4.2.2 - ID organizace" "Identifikátor organizace plátce"
* hlavicka.uhrada.infoOPlatci.organizace 0..1 Base "A.1.4.2.3 - Organizace plátce" "Organizace plátce"
* hlavicka.uhrada.infoOPlatci.adresa 0..1 Address "A.1.4.2.4 - Adresa" "Adresa plátce"
* hlavicka.uhrada.infoOPlatci.zeme 1..1 CodeableConcept "A.1.4.2.5 - Země" "Země plátce"
* hlavicka.uhrada.infoOPlatci.telekom 0..* ContactPoint "A.1.4.2.6 - Telekom" "Telekomunikační spojení na plátce."
* hlavicka.uhrada.kodNahrady 0..1 CodeableConcept "A.1.4.3 - Kód náhrady" "PZS je povinno indikovat úrazy a jiná poškození zdraví osob, kterým poskytlo zdravotní péči, pokud má důvodné podezření, že úraz nebo jiné poškození zdraví byly způsobeny jednáním právnické nebo fyzické osoby, dle číselníku VZP „Náhrady za zdravotní péči."
* hlavicka.objednatel 1..* Base "A.1.5 - Objednatel" "Objednatel provedení zdravotní služby."
* hlavicka.objednatel.identifikator 1..* Identifier "A.1.5.1 - Identifikátor zadavatele objednávky" "Identifikační číslo zdravotnického pracovníka –  národní ID zdravotnického pracovníka vedený v KRZP. V případě, že není objednávka zadána zdravotnickým pracovníkem, ale například samotným pacientem, měl by být použit osobní identifikátor RID (případně DRID)."
* hlavicka.objednatel.jmeno 1..1 HumanName "A.1.5.2 - Jméno zadavatele objednávky" "Jméno objednavatele"
* hlavicka.objednatel.adresa 1..1 Base "A.1.5.3 - Kontaktní údaje zadavatele objednávky" "Kontaktní údaje zadavatele objednávky (adresa a telekomunikační údaje)."
* hlavicka.objednatel.organizace 0..1 Base "A.1.5.4 - Organizace zadavatele objednávky" "Organizace zadavatele objednávky (poskytovatel zdravotních služeb)."
* hlavicka.provadejici 0..1 Base "A.1.6 - Provádějící" "Předpokládaný Provádějící žádanky (u neadresné žádanky nebude Provádějící uveden)."
* hlavicka.provadejici.id 0..1 Identifier "A.1.6.1 -ID Provádějícího" "Identifikátor, který se vztahuje na tuto osobu v této roli. Identifikátor z KRZP."
* hlavicka.provadejici.jmeno 0..1 HumanName "A.1.6.2 - Jméno Provádějícího" "Jméno a příjmení osoby provádějícíe žádanky."
* hlavicka.provadejici.idOrganizace 0..1 Identifier "A.1.6.3 - ID organizace Provádějícího" "Identifikátor organizace provádějícího, který se používá k identifikaci organizace v různých informačních systémech. V ČR se využívá KRPZS identifikátor tedy IČO "
* hlavicka.provadejici.organizace 0..1 Base "A.1.6.4 - Organizace Provádějícího" "Název, identifikační a kontaktní údaje zdravotnického zařízení Provádějícího, případně také pracoviště Provádějícího."
* hlavicka.dodatecniPrijemci 0..* Base "A.1.7 - Příjemce nálezu" "Dodateční příjemci nálezu kromě objednatele"
* hlavicka.dodatecniPrijemci.identifikator 0..* Identifier "A.1.7.1 - Identifikátor příjemce" "I Identifikátor, který se vztahuje na tuto osobu v této roli."
* hlavicka.dodatecniPrijemci.jmeno 0..1 HumanName "A.1.7.2 - Jméno příjemce" "Jméno a příjmení osoby příjemce."
* hlavicka.dodatecniPrijemci.idOrganizace 0..1 Identifier "A.1.7.3 - ID organizace" "Identifikátor organizace příjemce nálezu, který se používá k identifikaci organizace v různých informačních systémech."
* hlavicka.dodatecniPrijemci.organizace 0..1 Base "A.1.7.4 - Organizace příjemce" "Název, identifikační a kontaktní údaje zdravotnického zařízení příjemce, případně také pracoviště příjemce."
* hlavicka.metadataDokumentu 1..1 Base "A.1.8 - Metadata dokumentu" "Dokument metadata"
* hlavicka.metadataDokumentu.idDokumentu 1..1 Identifier "A.1.8.1 - ID dokumentu" "Identifikátor dokumentu"
* hlavicka.metadataDokumentu.kategorie 1..1 CodeableConcept "A.1.8.2 - Kategorie" "Kategorie elektronického zdravotního záznamu (EHR)."
* hlavicka.metadataDokumentu.stav 1..1 CodeableConcept "A.1.8.3 - Stav" "Stav dokumentu (předběžný, finální, doplněný, opravený atp.)."
* hlavicka.metadataDokumentu.datumACas 1..1 dateTime "A.1.8.4 - Datum a čas vytvoření" "Datum a čas vytvoření dokumentu."
* hlavicka.metadataDokumentu.nazev 1..1 string "A.1.8.5 - Název dokumentu" "Název dokumentu"
* hlavicka.metadataDokumentu.spravce 1..1 Base "A.1.8.6 - Správce dokumentu" "Název a identifikační údaje subjektu, který dokument spravuje. Alias technický správce dokumentu."
* hlavicka.metadataDokumentu.duvernost 1..1 CodeableConcept "A.1.8.7 - Důvěrnost" "Stupeň důvěrnosti dokumentu (a jeho obsahu)."
* hlavicka.metadataDokumentu.jazyk 1..1 CodeableConcept "A.1.8.8 - Jazyk" "Jazyk, v němž je dokument napsán (narativní část dokumentu)."
* hlavicka.metadataDokumentu.verze 0..1 string "A.1.8.9 - Verze" "Verze dokumentu"
* hlavicka.elektronickyPodpis 1..* Base "A.1.9 - Elektronické podpisy" "Elektronické podpisy dle zákona 327/2011 §54a"
* hlavicka.elektronickyPodpis.elektronickyPodpis 1..1 Signature "A.1.9.1 - Elektronický podpis" "Elektronický podpis nebo pečeť dokumentu."
* hlavicka.elektronickyPodpis.casoveRazitko 0..1 instant "A.1.9.2 - Elektronické časové razítko" "Elektronické časové razítko "
* telo 1..1 Base "A.2 - Tělo dokumentu (K)" "Tělo dokumentu K-žádanky obsahující informace o objednávce,\nklinické údaje, úhradu, termín návštěvy a specifikaci požadovaných služeb."
* telo.informaceOZadance 0..1 Base "A.2.1 - Informace o objednávce" "Základní informace o žádance včetně diagnóz a důvodu žádosti."
* telo.informaceOZadance.detailyObjednavky 0..* Base "A.2.1 - Informace o objednávce" "Informace o objednávce"
* telo.informaceOZadance.detailyObjednavky.identifikator 1..* Identifier "A.2.1.1 - ID objednávky" "Identifikátor objednávky vyšetření."
* telo.informaceOZadance.detailyObjednavky.datumACas 1..1 dateTime "A.2.1.2 - Datum a čas objednávky" "Datum a čas zadání objednávky."
* telo.informaceOZadance.detailyObjednavky.datumACasPozadovanehoProvedeni 0..1 dateTime "A.2.1.3 - Datum a čas požadovaného provedení" "Datum a čas požadovaného provedení"
* telo.informaceOZadance.detailyObjednavky.urgentnost 0..1 CodeableConcept "A.2.1.4 - Urgentnost objednávky" "Urgentnost objednávky (rutinní, urgentní, statim).  \n- Preferovaný systém: HL7:RequestPriority"
* telo.informaceOZadance.detailyObjednavky.textObjednavky 0..1 string "A.2.1.5 - Text objednávky" "Textový popis objednávky či doplňující požadavky, specifické pro jednotlivé typy objednávek, pokud je nelze vyjádřit formalizovaně."
* telo.informaceOZadance.detailyObjednavky.informaceProPacienta 0..1 string "A.2.1.6 - Informace pro pacienta" "Instrukce pro pacienta související s objednávkou. Např. na lačno apod."
* telo.informaceOZadance.duvodObjednavky 1..1 Base "A.2.2 - Odůvodnění vyšetření (důvod objednávky)" "Odůvodnění vyšetření (důvod objednávky)"
* telo.informaceOZadance.duvodObjednavky.problem 1..* CodeableConcept "A.2.2.1 - Popis problému / diagnózy / stavu – indikační diagnóza" "Důvod vystavení objednávky k vyšetření vyjádřený strukturovaným textem a/nebo kódem.\n- Preferovaný systém: MKN-10\n- Preferovaný systém: Orphacode"
* telo.informaceOZadance.duvodObjednavky.klinickaOtazkaKod 0..* CodeableConcept "A.2.2.2 - Klinická otázka kódem" "kódovaná informace z 2.2.3, pokud je zadána\n- Preferovaný systém: SNOMED CT"
* telo.informaceOZadance.duvodObjednavky.klinickaOtazkaText 1..1 string "A.2.2.3 - Klinická otázka textem" "Klinická otázka, na kterou má požadované vyšetření nebo péče odpovědět. Mapuje se na text klinické sekce; pokud popisuje klinický problém reprezentovaný jako Condition, také na CZ_ClinicalQuestion.code.text."
* telo.informaceOZadance.duvodObjednavky.duvodKod 0..* CodeableConcept "A.2.2.4 - Důvod objednávky kódem" "kódovaná informace z 2.2.5, pokud je zadána\n- Preferovaný systém: SNOMED CT ReasonCodelist 243796009"
* telo.informaceOZadance.duvodObjednavky.duvodText 0..1 string "A.2.2.5 - Důvod objednávky textem" "Důvod vystavení objednávky k vyšetření vyjádřený volným textem (např. \\\"3 týdny neustupující kašel\\\")"
* telo.klinickaUdalost 0..1 Base "A.2.3 - Klinická událost" "Informace o klinické události související s požadavkem."
* telo.klinickaUdalost.identifikator 1..* Identifier "A.2.3.1 - ID klinické události" "Jednoznačný, globálně unikátní identifikátor klinické události, k němuž se objednávka vztahuje."
* telo.klinickaUdalost.typ 0..* CodeableConcept "A.2.3.2 - Typ klinické události" "Typ klinické události dle číselníku typů. (např. hospitalizace, ambulantní návštěva apod.)."
* telo.klinickaUdalost.dalsiInformace 0..1 string "A.2.3.3 - Další informace o klinické události" "Typ poskytovaných služeb, období či délka klinické události, vazba na další klinické události apod."
* telo.uhrada 1..* Base "A.2.4 - Úhrada" "Informace o typu úhrady zdravotní služby."
* telo.uhrada.zpusob 1..1 CodeableConcept "A.2.4.1 - Způsob úhrady" "Method of payment for the order (health coverage, paid by the patient, other)"
* telo.uhrada.informaceOPlatci 0..1 Base "A.2.4.2 - Informace o plátci" "Payer identification data and additional information regarding reimbursement other than from health coverage. Identification data includes the identifier, name of the organization or name of the payer, address of the payer and telecommunications connection."
* telo.uhrada.informaceOPlatci.jmeno 0..1 HumanName "A.2.4.2.1 - Jméno plátce" "Jméno a příjmení plátce"
* telo.uhrada.informaceOPlatci.identifikatorOrganizace 0..* Identifier "A.2.4.2.2 - ID organizace plátce" "Identifikátor organizace plátce"
* telo.uhrada.informaceOPlatci.organizace 0..1 Base "A.2.4.2.3 - Organizace plátce" "Organizace plátce"
* telo.uhrada.informaceOPlatci.adresa 0..1 Address "A.2.4.2.4 - Adresa" "Adresa plátce"
* telo.uhrada.informaceOPlatci.zeme 1..1 CodeableConcept "A.2.4.2.5 - Země" "Země, ze které úhrada pochází"
* telo.uhrada.informaceOPlatci.telekom 0..* ContactPoint "A.2.4.2.6 - Telekom" "Telekomunikační spojení na osobu zodpovědnou za úhrady."
* telo.uhrada.komentar 0..1 string "A.2.4.3 - Komentář" "Případné upřesnění platby"
* telo.terminVysetreni 0..1 Base "A.2.5 - Termín návštěvy" "Informace o plánovaném termínu návštěvy nebo objednání pacienta."
* telo.terminVysetreni.id 0..1 Identifier "A.2.5.1 - Termín ID" "Identifikátor záznamu termínu návštěvy"
* telo.terminVysetreni.stav 1..1 CodeableConcept "A.2.5.2 - Stav termínu" "Stav termínu (navržený, potvrzený, zrušený).\nPreferovaný systém: hl7:valueset-appointmentstatus"
* telo.terminVysetreni.popis 1..1 string "A.2.5.3 - Popis" "Stručný popis termínu návštěvy pro zobrazení v seznamu termínů."
* telo.terminVysetreni.datumACas 0..1 dateTime "A.2.5.4 - Plánovaný čas" "Datum a čas návštěvy"
* telo.terminVysetreni.delkaVysetreni 0..1 Duration "A.2.5.5 - Délka vyšetření" "Délka vyšetření"
* telo.terminVysetreni.komentar 0..1 string "A.2.5.6 - Komentář" "Doplňující komentář"
* telo.terminVysetreni.instrukceProPacienta 0..1 string "A.2.5.7 - Instrukce pro pacienta" "Instrukce pro pacienta (např. dostavte se 15 minut napřed, nalačno, zajistěte si odvoz apod.)."
* telo.terminVysetreni.misto 1..1 Base "A.2.5.8 - Místo" "Název a adresa pracoviště, kde byl termín návštěvy sjednán."
* telo.informaceOVzorku 0..* Base "A.2.6 - Informace o vzorku" "Informace o vzorku souvisejícím s žádankou."
* telo.informaceOVzorku.identifikator 1..* Identifier "A.2.6.1 - Identifikátor vzorku" "Jednoznačný identifikátor vzorku v daném kontextu."
* telo.informaceOVzorku.druhOrganismu 0..1 CodeableConcept "A.2.6.2 - Druh organismu" "Biologický druh subjektu u nehumánních vzorků."
* telo.informaceOVzorku.material 0..1 CodeableConcept "A.2.6.3 - Materiál" "Typ materiálu vzorku."
* telo.informaceOVzorku.datumACasOdberu 1..1 dateTime "A.2.6.4 - Datum a čas odběru" "Datum a čas odběru nebo dokončení odběru."
* telo.informaceOVzorku.datumACasTransportu 0..1 dateTime "A.2.6.5 - Datum a čas transportu" "Datum a čas zahájení transportu vzorku."
* telo.informaceOVzorku.typVzorku 0..1 CodeableConcept "A.2.6.6 - Typ vzorku" "Typ vzorku nebo odebraného materiálu."
* telo.informaceOVzorku.anatomickaLokalizace 0..1 CodeableConcept "A.2.6.7 - Anatomická lokalizace" "Místo odběru materiálu včetně případné laterality."
* telo.informaceOVzorku.morfologie 0..1 CodeableConcept "A.2.6.8 - Morfologie" "Morfologická abnormalita místa odběru."
* telo.informaceOVzorku.nastroj 0..1 CodeableConcept "A.2.6.9 - Nástroj" "Nástroj nebo pomůcka použitá při odběru."
* telo.informaceOVzorku.metodaOdberu 0..1 CodeableConcept "A.2.6.10 - Metoda odběru" "Postup nebo metoda odběru."
* telo.informaceOVzorku.zdrojoveZarizeni 0..1 CodeableConcept "A.2.6.11 - Zdrojové zařízení" "Zařízení, ze kterého vzorek pochází, pokud nebyl odebrán přímo pacientovi."
* telo.informaceOVzorku.mistoOdberu 0..1 CodeableConcept "A.2.6.12 - Místo odběru" "Prostor nebo prostředí, kde byl materiál odebrán."
* telo.informaceOVzorku.poznamka 0..1 string "A.2.6.13 - Poznámka" "Volná poznámka ke vzorku."
* telo.informaceOVzorku.nadoba 0..* Base "A.2.6.14 - Nádoba" "Informace o odběrové nádobě."
* telo.informaceOVzorku.nadoba.typ 0..1 CodeableConcept "A.2.6.14.1 - Typ" "Typ odběrové nádoby včetně případných aditiv."
* telo.informaceOVzorku.nadoba.pocet 0..1 integer "A.2.6.14.2 - Počet" "Počet identických nádob se vzorkem."
* telo.informaceOVzorku.nadoba.idZarizeni 1..1 Identifier "A.2.6.14.3 - ID zařízení" "Strojově čitelný identifikátor nádoby."
* telo.informaceOVzorku.nadoba.oznaceni 0..1 Identifier "A.2.6.14.4 - Označení" "Čitelný identifikátor nádoby."
* telo.informaceOVzorku.dalsiUdaje 0..1 Base "A.2.6.15 - Další formalizované údaje" "Doplňující formalizované údaje o vzorku."
* telo.informaceOVzorku.dalsiUdaje.datum 0..1 date "A.2.6.15.1 - Datum" "Datum zjištění údaje, pokud se liší od data žádanky."
* telo.informaceOVzorku.dalsiUdaje.kod 1..1 CodeableConcept "A.2.6.15.2 - Kód" "Kód určující význam doplňujícího údaje."
* telo.informaceOVzorku.dalsiUdaje.hodnota 0..1 Narrative "A.2.6.15.3 - Hodnota" "Hodnota údaje včetně jednotky."
* telo.informaceOVzorku.odberatel 0..1 Base "A.2.6.16 - Odběratel" "Identifikace osoby nebo subjektu, který vzorek odebral."
* telo.informaceOVzorku.odberatel.identifikator 1..* Identifier "A.2.6.16.1 - Identifikátor odběratele" "Identifikátor odběratele vzorku."
* telo.informaceOVzorku.odberatel.jmeno 1..1 HumanName "A.2.6.16.2 - Jméno odběratele" "Jméno odběratele vzorku."
* telo.informaceOVzorku.odberatel.kontakt 1..1 ContactPoint "A.2.6.16.3 - Kontakt odběratele" "Kontaktní údaje odběratele vzorku."
* telo.informaceOVzorku.odberatel.organizace 0..1 Base "A.2.6.16.4 - Organizace odběratele" "Organizace, pod kterou odběratel vzorku působí."
* telo.klinickeInformace 1..1 Base "A.3.1 - Podpůrné informace" "Klinické a další podpůrné informace relevantní pro provedení žádanky a interpretaci výsledků."
* telo.klinickeInformace.biometrickeUdaje 0..1 Base "A.3.1.1 - Biometrické údaje" "Biometrické údaje relevantní pro provedení žádanky."
* telo.klinickeInformace.biometrickeUdaje.vaha 0..1 Base "A.3.1.1.1 - Váha" "Údaj o tělesné hmotnosti pacienta."
* telo.klinickeInformace.biometrickeUdaje.vaha.hodnota 1..1 Quantity "A.3.1.1.1.1 - Hodnota váhy" "Hodnota váhy včetně jednotky."
* telo.klinickeInformace.biometrickeUdaje.vaha.kod 1..1 CodeableConcept "A.3.1.1.1.2 - Kód váhy" "Kód určující význam údaje o váze."
* telo.klinickeInformace.biometrickeUdaje.vaha.datumACas 0..1 dateTime "A.3.1.1.1.3 - Datum a čas váhy" "Datum a čas zjištění váhy, pokud se liší od data žádanky."
* telo.klinickeInformace.biometrickeUdaje.vyska 0..1 Base "A.3.1.1.2 - Výška" "Údaj o tělesné výšce pacienta."
* telo.klinickeInformace.biometrickeUdaje.vyska.hodnota 1..1 Quantity "A.3.1.1.2.1 - Hodnota výšky" "Hodnota výšky včetně jednotky."
* telo.klinickeInformace.biometrickeUdaje.vyska.kod 1..1 CodeableConcept "A.3.1.1.2.2 - Kód výšky" "Kód určující význam údaje o výšce."
* telo.klinickeInformace.biometrickeUdaje.vyska.datumACas 0..1 dateTime "A.3.1.1.2.3 - Datum a čas výšky" "Datum a čas zjištění výšky, pokud se liší od data žádanky."
* telo.klinickeInformace.dalsiRelevantniKlinickeInformace 0..1 Base "A.3.1.2 - Další relevantní klinické informace" "Další klinické informace relevantní pro provedení žádanky nebo interpretaci výsledků."
* telo.klinickeInformace.dalsiRelevantniKlinickeInformace.kod 0..* CodeableConcept "A.3.1.2.1 - Kód informace (vedlejší diagnoza)" "Diagnózy a jiné klinické informace důležité pro provedení žádanky nebo interpretaci výsledků."
* telo.klinickeInformace.dalsiRelevantniKlinickeInformace.text 0..1 string "A.3.1.2.2 - Text informace" "Textový popis dalších relevantních klinických informací."
* telo.klinickeInformace.medikace 0..* Base "A.3.1.3 - Medikace" "Informace o medikaci mající vliv na průběh nebo výsledek vyšetření či péče."
* telo.klinickeInformace.medikace.identifikator 0..* Identifier "A.3.1.3.1 - ID medikace" "Identifikátor medikace."
* telo.klinickeInformace.medikace.kod 0..* code "A.3.1.3.2 - Kód medikace" "Kód medikace."
* telo.klinickeInformace.medikace.mnozstvi 0..1 Ratio "A.3.1.3.3 - Množství" "Množství nebo dávka medikace."
* telo.klinickeInformace.implantat 0..* Base "A.3.1.4 - Implantát" "Seznam implantátů nebo pomůcek majících vliv na provedení žádanky či interpretaci výsledků."
* telo.klinickeInformace.implantat.typ 1..1 CodeableConcept "A.3.1.4.1 - Druh implantátu" "Druh implantátu."
* telo.klinickeInformace.implantat.identifikator 0..* Identifier "A.3.1.4.2 - ID implantátu" "Normalizovaný identifikátor implantátu, např. UDI."
* telo.klinickeInformace.implantat.model 1..1 string "A.3.1.4.3 - Konkrétní model" "Konkrétní model implantátu."
* telo.klinickeInformace.implantat.castTela 0..* CodeableConcept "A.3.1.4.4 - Část těla" "Část těla, kde je implantát umístěn."
* telo.klinickeInformace.urgentniInformace 0..1 Base "A.3.1.5 - Urgentní informace" "Urgentní informace důležité pro realizaci žádanky."
* telo.klinickeInformace.urgentniInformace.alergieAIntolerance 1..* CodeableConcept "A.3.1.5.1 - Alergie a intolerance" "Alergie a intolerance důležité pro realizaci žádanky nebo interpretaci výsledků."
* telo.klinickeInformace.urgentniInformace.varovani 0..* string "A.3.1.5.2 - Varování" "Varování a upozornění mající vliv na realizaci žádanky nebo interpretaci výsledků."
* telo.klinickeInformace.omezeniPohyblivostiPacienta 0..1 Base "A.3.1.6 - Omezení pohyblivosti pacienta" "Strukturovaná informace o omezení pohyblivosti pacienta."
* telo.klinickeInformace.omezeniPohyblivostiPacienta.datumACas 1..1 dateTime "A.3.1.6.1 - Datum a čas informace" "Datum a čas zjištění informace o pohyblivosti."
* telo.klinickeInformace.omezeniPohyblivostiPacienta.kod 1..1 CodeableConcept "A.3.1.6.2 - Kód informace" "Kód typu hodnocené pohyblivosti."
* telo.klinickeInformace.omezeniPohyblivostiPacienta.hodnota 1..1 CodeableConcept "A.3.1.6.3 - Hodnota informace" "Hodnota hodnocení pohyblivosti pacienta."
* telo.klinickeInformace.ockovani 0..* CodeableConcept "A.3.1.7 - Očkování" "Informace o očkování, pokud jsou relevantní."
* telo.klinickeInformace.dalsiFormalizovaneUdaje 0..* Base "A.3.1.8 - Další formalizované údaje" "Další formalizované údaje sdělované provádějícímu pracovišti."
* telo.klinickeInformace.dalsiFormalizovaneUdaje.datumACas 0..1 dateTime "A.3.1.8.1 - Datum" "Datum zjištění údaje, pokud se liší od data vystavení objednávky."
* telo.klinickeInformace.dalsiFormalizovaneUdaje.kod 1..1 CodeableConcept "A.3.1.8.2 - Kód" "Kód pozorování identifikující význam údaje."
* telo.klinickeInformace.dalsiFormalizovaneUdaje.hodnota 0..1 Narrative "A.3.1.8.3 - Hodnota" "Hodnota údaje včetně jednotky měření."
* telo.datoveElementyObjednavkyVysetreni 1..1 Base "A.3.2 - Datové elementy objednávky" "Strukturovaná specifikace požadovaných zdravotních služeb nebo vyšetření."
* telo.datoveElementyObjednavkyVysetreni.pozadovaneVysetreni 1..* Base "A.3.2.1 - Požadované vyšetření" "Požadované vyšetření nebo služba."
* telo.datoveElementyObjednavkyVysetreni.pozadovaneVysetreni.kod 1..1 CodeableConcept "A.3.2.1.1 - Kód vyšetření" "Kód reprezentující vyšetření v rámci dohodnutého číselníku včetně jeho názvu."
* telo.datoveElementyObjednavkyVysetreni.pozadovaneVysetreni.nazev 0..1 string "A.3.2.1.2 - Název vyšetření" "Celý název vyšetření, pokud je odlišný od kódované informace."
* telo.datoveElementyObjednavkyVysetreni.pozadovaneVysetreni.poznamka 0..1 string "A.3.2.1.7 - Poznámka" "Poznámka objednatele k žádanému vyšetření."
* telo.datoveElementyObjednavkyVysetreni.zavaznaAnamnestickaData 0..1 string "A.3.2.2 - Závažná anamnestická data" "Textový popis významných anamnestických údajů relevantních k požadovanému vyšetření nebo zdravotnímu stavu pacienta."
* telo.datoveElementyObjednavkyVysetreni.vysledkyVysetreni 0..1 string "A.3.2.3 - Výsledky provedených vyšetření" "Souhrn nebo výběr výsledků již provedených vyšetření, které jsou relevantní k aktuální objednávce nebo klinickému rozhodování."
* telo.datoveElementyObjednavkyVysetreni.diferencialniDiagnostickaRozvaha 0..1 string "A.3.2.4 - Diferenciálně diagnostická rozvaha" "Popis diferenciálně diagnostických úvah lékaře, včetně zvažovaných diagnóz a jejich zdůvodnění."
* telo.datoveElementyObjednavkyVysetreni.soucasnaLecba 0..1 string "A.3.2.5 - Současná léčba, medikace včetně dávkování" "Přehled aktuálně probíhající léčby pacienta, včetně užívaných léčivých přípravků a jejich dávkování."
* telo.datoveElementyObjednavkyVysetreni.zapujcenaDokumentace 0..1 string "A.3.2.6 - Zapůjčená dokumentace" "Seznam nebo popis zapůjčené zdravotnické dokumentace přiložené k objednávce (např. obrazová dokumentace, zprávy z jiných pracovišť)."
* telo.odkazyNaObjednavkyPlanovanePece 0..1 Base "A.3.3 - Odkazy na objednávky plánované péče navazující na tuto žádanku" "Odkazy na související objednávky plánované péče."
* telo.odkazyNaObjednavkyPlanovanePece.identifikator 0..1 Identifier "A.3.3.1 - Identifikátor objednávky plánované péče" "Identifikátor související objednávky plánované péče."
* telo.odkazyNaObjednavkyPlanovanePece.nazev 1..1 string "A.3.3.2 - Název" "Název související objednávky plánované péče."
* telo.ostatniPodpurneInformace 0..* Base "A.3.4 - Ostatní podpůrné informace" "Odkazy na další podpůrné informace související s žádankou."
* telo.ostatniPodpurneInformace.identifikator 0..1 Identifier "A.3.4.1 - Identifikátor podpůrné informace" "Identifikátor související podpůrné informace."
* telo.ostatniPodpurneInformace.nazev 1..1 string "A.3.4.2 - Název" "Název podpůrné informace pro zobrazení."
* prezentovanaForma 0..1 Base "A.4 - Prezentovaná forma" "Lidsky čitelná reprezentace dokumentu."
* prezentovanaForma.vizualniPodoba 0..1 Base "A.4 - Vizuální podoba" "Vizuální podoba dokumentu"
* prezentovanaForma.typObsahu 0..1 CodeableConcept "A.4.1 - Typ obsahu" "Typ obsahu - je  požadován MIME typ"
* prezentovanaForma.jazyk 0..1 CodeableConcept "A.4.2 - Jazyk obsahu" "Jazyk obsahu - je požadována hodnata z HL7 valueset Languages"
* prezentovanaForma.data 1..1 base64Binary "A.4.3 - Data obsahu" "Data v base64"
* prezentovanaForma.url 0..1 url "A.4.4 - URL obsahu" "Uri kde lze data nalézt"
* prezentovanaForma.nazev 1..1 string "A.4.5 - Název obsahu" "Titulek, který bude zobrazen před daty"
* prezentovanaForma.vytvoreni 0..1 dateTime "A.4.6 - Datum vytvoření" "Datum, kdy byl obsah poprvé vytvořen"
* prilohy 0..* Base "A.5 - Přílohy" "Přílohy připojené ke K-žádance."
* prilohy.typObsahu 0..1 CodeableConcept "A.5.1 - Typ obsahu" "Typ obsahu - je  požadován MIME typ"
* prilohy.jazyk 0..1 CodeableConcept "A.5.2 - Jazyk obsahu" "Jazyk obsahu - je požadována hodnata z HL7 valueset Languages"
* prilohy.data 1..1 base64Binary "A.5.3 - Data obsahu" "Data v base64"
* prilohy.url 0..1 url "A.5.4 - URL obsahu" "Uri kde lze data nalézt"
* prilohy.nazev 1..1 string "A.5.5 - Název obsahu" "Titulek, který bude zobrazen před daty"
* prilohy.vytvoreni 0..1 dateTime "A.5.6 - Datum vytvoření" "Datum, kdy byl obsah poprvé vytvořen"
