"""Render/check shared CZ Core header mappings for Order and sibling IMG-Order.

Edit input/data/header-mapping.json, then run this script. IMG keeps standalone
copies of the generated includes so its IG can be built independently.
"""
import argparse
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORE = 'https://hl7.cz/fhir/core/'
PROFILES = {
    'CZ_PatientCore': 'cz-patient-core',
    'CZ_PractitionerCore': 'cz-practitioner-core',
    'CZ_PractitionerRoleCore': 'cz-practitionerrole-core',
    'CZ_OrganizationCore': 'cz-organization-core',
    'CZ_RelatedPersonCore': 'cz-relatedPerson-core',
    'CZ_Coverage': 'cz-coverage',
}

def esc(value):
    return html.escape(value, quote=False)

def profile_links(value):
    parts = []
    for part in value.split(' / '):
        match = re.fullmatch(r'(\w+) \((.*?)\)', part)
        if not match:
            raise ValueError(f'Unsupported target profile: {part}')
        kind, name = match.groups()
        if name in PROFILES:
            href = CORE + 'StructureDefinition-' + PROFILES[name] + '.html'
        elif name in ('{{ include.composition }}', '{{ include.bundle }}'):
            href = 'StructureDefinition-' + name + '.html'
        else:
            raise ValueError(f'Unknown profile: {name}')
        parts.append(f'<a href="{href}">{esc(part)}</a>')
    return ' / '.join(parts)

def render(rows, lang):
    relationships = {'equivalent': 'ekvivalentní', 'related': 'související', 'unmatched': 'bez přímého mapování'} if lang == 'cs' else {
        'equivalent': 'equivalent', 'related': 'related', 'unmatched': 'no direct mapping'}
    output = ['<!-- Generated from input/data/header-mapping.json by scripts/sync-header-mapping.py. -->']
    for row in rows:
        model = '{{ include.' + row['model'] + '_model }}'
        source = f'<a href="StructureDefinition-{model}.html">{esc(row["source"])}</a>'
        cells = [source, esc(row['label'][lang]), relationships[row['relationship']],
                 profile_links(row['profile']), esc(row['element']),
                 esc(row['navigation']), esc(row['note'][lang])]
        output.append('<tr data-mapping-id="' + row['code'] + '">' + ''.join('<td>' + c + '</td>' for c in cells) + '</tr>')
    return '\n'.join(output) + '\n'

def diagram(header, composition, request, bundle):
    lines = ['@startuml', "' Generated by scripts/sync-header-mapping.py",
             'hide circle', 'hide members', 'skinparam linetype ortho',
             f'class "{header}" as Header <<LogicalModel>> [[StructureDefinition-{header}.html]]']
    profiles = [(name, CORE + 'StructureDefinition-' + identifier + '.html') for name, identifier in PROFILES.items()]
    profiles += [(name, 'StructureDefinition-' + name + '.html') for name in (composition, request, bundle)]
    for index, (name, link) in enumerate(profiles):
        lines += [f'class "{name}" as Target{index} <<Profile>> [[{link}]]', f'Header ..> Target{index}']
    lines.append('@enduml')
    return '\n'.join(lines) + '\n'

GUIDANCE = {
    'cs': '''<div xmlns="http://www.w3.org/1999/xhtml">
  <p>Hlavička A.1 používá společné mapování IMG, K a FT na CZ Core 1.0.0. Liší se pouze doménový profil Composition, ServiceRequest a Bundle a názvy zdrojových modelů. Obě jazykové tabulky odkazují na české logické modely; jazyk mění popisky, nikoli FHIR cíle.</p>
  <p>Sloupec Reference uvádí navigaci ke zdroji, sloupec Prvek jeho relativní element. Zápis section[název] označuje slice profilu, nikoli doslovný FHIRPath; resolve() znamená průchod referencí. Ve skutečném FHIRPath se sekce vybírá podle jejího kódu. Doménový ServiceRequest je v section[orderInformation].entry. Stejné reference se znovu používají pro dokument a příslušný požadavek.</p>
  <p>CZ_PractitionerRoleOrder je specializace z balíčku CZ Core. Tabulka zobrazuje společný základ CZ_PractitionerRoleCore; omezení konkrétního profilu žádanky zůstávají závazná. Chybějící přímé mapování identifikátoru kontaktní osoby je uvedeno výslovně. Čas podpisu není samostatný kryptografický token časového razítka.</p>
</div>
''',
    'en': '''<div xmlns="http://www.w3.org/1999/xhtml">
  <p>Header A.1 uses the same CZ Core 1.0.0 mapping for IMG, K and FT. Only the domain Composition, ServiceRequest and Bundle profiles and source model names differ. Both language tables reference the Czech logical models; language changes labels, not FHIR targets.</p>
  <p>The Reference column navigates to the resource; Element is relative to that resource. section[name] denotes a profile slice, not literal FHIRPath; resolve() traverses a reference. Executable FHIRPath selects sections by their codes. The domain ServiceRequest is in section[orderInformation].entry. Reuse the same resources for document and applicable request references.</p>
  <p>CZ_PractitionerRoleOrder is a specialization from the CZ Core package. The table shows the common CZ_PractitionerRoleCore base; constraints of each order profile still apply. The lack of a direct mapping for a contact person's identifier is stated explicitly. Signing time is not a standalone cryptographic timestamp token.</p>
</div>
''',
}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--img-root', type=Path, default=ROOT.parent / 'RTG')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    img = args.img_root.resolve()
    if not (img / 'sushi-config.yaml').is_file():
        parser.error('IMG-Order checkout not found; supply --img-root')
    rows = json.loads((ROOT / 'input/data/header-mapping.json').read_text(encoding='utf-8'))
    order_models = dict(header='LMHeaderOrder', subject='LMSubjectOrderCz', payer='LMPayerOrderCz',
                        coverage='LMCoverageOrderCz', author='LMAuthorOrderCz', performer='LMRequestedPerformerOrderCz',
                        recipient='LMAdditionalRecipientCz', metadata='LMDocumentMetadataCz', signature='LMDigitalSignatureOrderCz')
    img_models = dict(header='logHeaderImagingOrder', subject='logSubjectCz', payer='logPayerCz',
                      coverage='logCoverageOrderCz', author='logAuthorCz', performer='logRequestedPerformerCz',
                      recipient='logAdditionalRecipientCz', metadata='logDocumentMetadataCz', signature='logdigitalSignatureCz')
    changed = []

    def output(path, text):
        current = path.read_text(encoding='utf-8') if path.exists() else None
        if current == text:
            return
        changed.append(str(path))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8', newline='\n')

    for lang in ('cs', 'en'):
        for root in (ROOT, img):
            output(root / f'input/includes/header-core-map-{lang}.xml', render(rows, lang))
            output(root / f'input/includes/header-core-guidance-{lang}.xml', GUIDANCE[lang])
        pages = [(ROOT, 'K-Header-map' + ('' if lang == 'cs' else '-en') + '.xml', 'KOrderCompositionCz', 'KOrderServiceRequestCz', 'BundleOrderCz', order_models, 'provadejici'),
                 (ROOT, 'FT-Header-map' + ('' if lang == 'cs' else '-en') + '.xml', 'FTOrderCompositionCz', 'FTServiceRequestCz', 'BundleOrderCz', order_models, 'provadejici'),
                 (img, 'Header-map' + ('-cs' if lang == 'cs' else '') + '.xml', 'cz-compositionImageOrder', 'cz-imagingOrderInformation', 'cz-bundleImageOrder', img_models, 'zpracovatel')]
        for root, filename, composition, request, bundle, models, performer in pages:
            path = root / 'input/pagecontent' / filename
            text = path.read_text(encoding='utf-8')
            params = dict(composition=composition, service_request=request, bundle=bundle, performer_element=performer,
                          **{key + '_model': value for key, value in models.items()})
            include = '{% include header-core-map-' + lang + '.xml ' + ' '.join(f'{k}="{v}"' for k, v in params.items()) + ' %}'
            text, count = re.subn(r'<tbody>.*?</tbody>', '<tbody>\n        ' + include + '\n      </tbody>', text, flags=re.S)
            assert count == 1, filename
            text = re.sub(r'\s*<li><strong>(?:Zdrojový mapovací soubor|Source mapping file):</strong>.*?</li>', '', text)
            guidance = '{% include header-core-guidance-' + lang + '.xml %}'
            if guidance not in text:
                # Place guidance before the mapping table, outside table content.
                text = re.sub(r'(<div class="table-wrap">\s*<table)', guidance + '\n\n  ' + r'\1', text, count=1)
            context = '<p class="header-domain-context">' + '; '.join(
                f'{kind}: <a href="StructureDefinition-{identifier}.html">{identifier}</a>'
                for kind, identifier in [('Composition', composition), ('ServiceRequest', request), ('Bundle', bundle)]) + '</p>'
            if 'class="header-domain-context"' in text:
                text = re.sub(r'<p class="header-domain-context">.*?</p>', context, text)
            else:
                text = text.replace(guidance, guidance + '\n  ' + context)
            output(path, text)
            diagram_name = ('imgOrderHead-map' + ('-cs' if lang == 'cs' else '') if root == img else filename.split('-Header')[0] + '-Header-map')
            output(root / 'input/images-source' / (diagram_name + '.plantuml'),
                   diagram(models['header'], composition, request, bundle))
    if args.check and changed:
        raise SystemExit('Out-of-date generated mapping files:\n' + '\n'.join(changed))
    print(f'{len(rows)} shared rows; six header pages checked' if args.check else f'Updated {len(changed)} files from {len(rows)} shared rows')

if __name__ == '__main__':
    main()
